import numpy as np
from gpu_model.update_particles_3d_kernel import update_particles_3d_kernel
from config.params import *
def update_particles_3d_gpu_step(
    step_in_window,
    head,
    f_step,
    d_x,
    d_y,
    d_z,
    d_particle_type,
    u_ref,
    v_ref,
    z_ref,
    z0,
    blh,
    Kxy,
    Kz_low,
    Kz_mid,
    Kz_high,
    dt,
    P_dep_surf,
    P_dep_nh4,
    P_conversion,
    P_wet_dep,
    w_mean,
    w_settle,
    d_particle_mass_g,
    timesteps_per_hour,
    d_depo,
    GRID_RES,
    minx,
    miny,
    nx,
    ny,
    DZ,
    z_cap,
    rng_states,
    blocks,
    threads,
    sshf,
    d_mass_budget,
    d_dem,
    dem_nx,
    dem_ny,
    dem_minx,
    dem_miny,
    dem_dx,
    dem_dy,
    d_dh_dx,
    d_dh_dy,
    d_initial_release_vz,
    d_seasonal_factor_step,
    ):
    n_part = d_x.shape[1]
    # 2D grid: blockIdx.x = time-slice j (0..step_in_window),
    #          blockIdx.y * blockDim.x + threadIdx.x = particle k
    blockspergrid_x = max(1, step_in_window + 1)
    blockspergrid_y = max(1, (n_part + threads - 1) // threads)

    update_particles_3d_kernel[(blockspergrid_x, blockspergrid_y), threads](
        d_x,
        d_y,
        d_z,
        d_particle_type,
        np.float32(float(u_ref)),
        np.float32(float(v_ref)),
        np.float32(float(z_ref)),
        np.float32(float(z0)),
        np.float32(float(blh)),
        np.float32(float(Kxy)),
        np.float32(float(Kz_low)),
        np.float32(float(Kz_mid)),
        np.float32(float(Kz_high)),
        np.float32(float(dt)),
        np.float32(float(P_dep_surf)),
        np.float32(float(P_dep_nh4)),
        np.float32(float(P_conversion)),
        np.float32(float(P_wet_dep)),
        np.float32(float(w_mean)),
        np.float32(float(w_settle)),
        d_particle_mass_g,
        np.float32(float(timesteps_per_hour)),
        d_depo,
        np.float32(float(GRID_RES)),
        np.float32(float(minx)),
        np.float32(float(miny)),
        np.int32(int(nx)),
        np.int32(int(ny)),
        np.float32(float(z_cap)),
        rng_states,
        np.int32(int(step_in_window)),
        np.int32(int(head)),
        np.int32(int(f_step)),
        d_dem,
        dem_nx,
        dem_ny,
        dem_minx,
        dem_miny,
        dem_dx,
        dem_dy,
        d_dh_dx,
        d_dh_dy,
        d_mass_budget,
        np.float32(float(CHANNELING_ALPHA)),
        np.float32(float(CHANNELING_Z_TOP)),
        np.float32(float(CHANNELING_SLOPE_REF)),
        np.float32(float(OROGRAPHIC_ALPHA)),
        np.float32(float(OROGRAPHIC_Z_TOP)),
        np.float32(float(sshf)),
        d_initial_release_vz,
        d_seasonal_factor_step
    )